"""The delivery incident report a supervisor would actually forward.

Everything in it is read back from stored state: the deterministic gate's own
threshold rows, the FFmpeg job results, the Grafana queries the agents were
bound to, and the human decisions. Nothing is re-generated by a model at export
time, so the report cannot say anything the product did not already show.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from .models import DeliveryRecord, JeopardyResult


def _hours(seconds: float) -> str:
    return f"{seconds / 3600:.2f} h"


def _prom_value(block: Any) -> str:
    try:
        payload = json.loads(block["content"][0]["text"])
        series = payload.get("data") or []
        if not series:
            return "no rows returned"
        if len(series) == 1:
            return str(series[0]["value"][1])
        return ", ".join(
            f"{[v for k, v in item['metric'].items() if k != '__name__'][0]}={item['value'][1]}"
            for item in series
        )
    except Exception:  # noqa: BLE001
        return "unavailable"


def render_report(record: DeliveryRecord, gate: JeopardyResult) -> str:
    lines: list[str] = []
    add = lines.append

    add(f"# Delivery report · {record.title}")
    add("")
    add(f"- Delivery ID: `{record.delivery_id}`")
    add(f"- Contractual date: {record.contractual_date.isoformat()}")
    add(f"- Penalty tier: {record.penalty_tier}")
    add(f"- Status: **{record.status}**")
    add(f"- Generated: {datetime.now(timezone.utc).isoformat()}")
    add("")
    add(
        "The delivery receiver in this build is simulated. Ingest, FFmpeg transcoding, QC, "
        "packaging, timings, logs and traces are real measurements."
    )
    add("")

    add("## Deterministic jeopardy gate")
    add("")
    add(f"Verdict **{gate.verdict}**, severity **{gate.severity}**. The model cannot set this.")
    add("")
    add("| Threshold | Met | Observed | Requires |")
    add("|---|---|---|---|")
    for item in gate.thresholds:
        add(f"| {item.name.replace('_', ' ')} | {'yes' if item.passed else 'no'} | {item.observed} | {item.required} |")
    add("")
    add(f"- Delivery window: {_hours(gate.delivery_window_seconds)}")
    add(f"- Measured work remaining: {_hours(gate.work_remaining_seconds)}")
    add(f"- Schedule budget: {_hours(gate.schedule_budget_seconds)}")
    add(f"- Projected completion: {gate.projected_completion.isoformat()}")
    if gate.hours_over:
        add(f"- Projected overrun: {gate.hours_over:.2f} h")
    add("")

    add("## Rendition jobs")
    add("")
    if record.jobs:
        add("| Spec | Status | Duration (s) | Exit | Retries | Bytes | Observed class | Failed QC |")
        add("|---|---|---|---|---|---|---|---|")
        for job in record.jobs:
            add(
                f"| {job.spec_name} | {job.status} | {job.duration_seconds:.3f} | {job.exit_code} | "
                f"{job.retries} | {job.output_bytes} | {job.failure_class or 'none'} | "
                f"{', '.join(job.qc_failures) or 'none'} |"
            )
        add("")
        add(
            "Failure classes are assigned by a deterministic classifier reading FFmpeg's stderr, "
            "exit status and QC output. No injected scenario label reaches it."
        )
    else:
        add("No pipeline run has been executed for this delivery yet.")
    add("")
    add(f"QC rules applied: {', '.join(record.qc_rules) or 'none'}.")
    add("")

    investigation = record.last_investigation or {}
    if investigation:
        add("## Agent investigation")
        add("")
        add(f"- Session: `{investigation.get('session_id')}`")
        add(f"- Model: {investigation.get('model')}")
        add(f"- Decision source: {investigation.get('decision_source')}")
        add(f"- Classification source: {investigation.get('classification_source')}")
        add(f"- Observability source: {investigation.get('observability_source')}")
        usage = investigation.get("token_usage") or {}
        if usage:
            add(f"- Tokens: {usage.get('input_tokens')} in, {usage.get('output_tokens')} out")
        add("")

        evidence = investigation.get("bound_evidence") or {}
        queries = evidence.get("queries") or {}
        if queries:
            add("### Evidence read through the official Grafana MCP server")
            add("")
            add("| Source | Query | Observed |")
            add("|---|---|---|")
            prometheus = evidence.get("prometheus") or {}
            for name, expression in queries.items():
                add(f"| PromQL | `{expression}` | {_prom_value(prometheus.get(name))} |")
            if evidence.get("loki_query"):
                add(f"| LogQL | `{evidence['loki_query']}` | see pipeline events |")
            if evidence.get("trace_id"):
                add(f"| Tempo | trace `{evidence['trace_id']}` | span tree retrieved |")
            add("")

        outputs = investigation.get("outputs") or {}
        for label, key in (("Watch", "watch"), ("Diagnose", "diagnose")):
            text = outputs.get(key)
            if isinstance(text, str) and text.strip():
                add(f"### {label}")
                add("")
                add(text.strip())
                add("")

        plan = investigation.get("remediation_plan")
        if plan:
            add("### Remediation options proposed")
            add("")
            add("| Action | Schedule cost | Reversible | Summary |")
            add("|---|---|---|---|")
            for option in plan.get("options", []):
                add(
                    f"| `{option['action']}` | {option['schedule_cost_seconds']:.0f} s | "
                    f"{'yes' if option['reversible'] else 'no'} | {option['summary']} |"
                )
            add("")
            add(f"Recommended: `{plan.get('recommended_action')}`. {plan.get('why_a_human_decides', '')}")
            add("")

    add("## Human decisions")
    add("")
    if record.decisions:
        add("| Decided at | Operator | Action | Verdict before | Verdict after |")
        add("|---|---|---|---|---|")
        for decision in record.decisions:
            add(
                f"| {decision.get('decided_at')} | {decision.get('operator_id')} | "
                f"`{decision.get('action')}` | {decision.get('verdict_before')} | "
                f"{decision.get('verdict_after')} |"
            )
    else:
        add("No remediation has been approved for this delivery.")
    add("")

    rule = record.alert_rule or {}
    add("## Grafana alert rule")
    add("")
    if rule.get("provisioned"):
        add(
            f"Provisioned through the official MCP tool `{rule.get('tool')}` "
            f"(UID `{rule.get('uid')}`) when this delivery was created."
        )
    else:
        add(f"Not provisioned: {rule.get('detail', 'unknown')}.")
    add("")
    add("---")
    add("")
    add(
        "SLATE is a delivery-SLO control tower. No agent can create jeopardy, change a "
        "contractual date, or execute a remediation without human approval."
    )
    return "\n".join(lines) + "\n"
